mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from tinyapp.views import UrlCreateView, UrlDetailView, UrlRedirectView, UrlDeleteView, UrlUpdateView, UserLoginView
from tinyapp.views import UrlListView
from tinyapp.views import UserRegistrationView
from tinyapp.views import SeeAdminsView
from django.contrib.auth.views import LogoutView, PasswordChangeView



urlpatterns = [
    path('', UrlListView.as_view(), name='user_list'),
    path('admin/', admin.site.urls),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('urls/', UrlListView.as_view(), name='urls'),
    path('urls/new/', UrlCreateView.as_view(), name='urls_new'),
    path('urls/<pk>/', UrlDetailView.as_view(), name = 'urls_detail'),
     path('urls/u/<short_url>/', UrlRedirectView.as_view(), name ='urls_redirect'),
    path('urls/delete/<pk>/', UrlDeleteView.as_view(), name = 'urls_delete'),
    path('urls/edit/<pk>/', UrlUpdateView.as_view(), name = 'urls_edit'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', LogoutView.as_view(), name='user_logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('change-password/', PasswordChangeView.as_view()),
    path('userlist/', SeeAdminsView.as_view(), name='users_list')
]

tinyapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
   pass
    
# Create your models here.
class Users (models.Model):
   first_name = models.CharField(max_length=20)
   last_name = models.CharField(max_length=30)
   username = models.CharField(max_length=30)
   email_address = models.CharField(max_length=30)
   password = models.CharField(max_length=15)

   def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Url(models.Model):
   short_url = models.URLField(max_length=10)
   long_url = models.URLField(max_length=200) 
   user = models.ForeignKey(User, on_delete=models.CASCADE) 
   date_created = models.DateField()

   def __str__(self):
        return self.short_url

   def get_absolute_url(self):
       return reverse('urls_detail', args=[str(self.pk)])

   

templates/admin.html
{% extends "base.html" %}

{% block title %}My TinyUsers{% endblock %}

{% block content %}

  <br/>
  <main class="container">
      {% if users %}
        <h3>TinyApp Users</h3>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Username</th>
                <th scope="col">First Name</th>   
                <th scope="col">Last Name</th>   
                <th scope="col">Email</th>
            </tr>
            </thead>
            <tbody>    
                {% for user in users %}
                    <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}     
            </tbody>
        </table>
      {%else%}
        <h1>You do not have permissions to view this page.</h1>
      {% endif %}
  </main>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous"
    />
    <title>{% block title %} {% endblock %}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">TinyApp</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              {% if user.is_authenticated == False %}
                <li class="nav-item {{ 'nav-link active' }}" > <a style ='color: white; text-decoration: none;' href="{% url 'register' %}">Register</a></li>
              {% endif %}
              <li class="nav-item {{ 'nav-link active' }}"> <a style ='color: white; text-decoration: none;' href="{% url 'urls' %}">My URLs</a></li>
              <li class="nav-item {{ 'nav-link active' }}"> <a style ='color: white; text-decoration: none;' href="{% url 'urls_new' %}">Create New URL</a></li>
              {% if perms.tinyapp.view_user %}
                <li class="nav-item {{ 'nav-link active' }}"> <a style ='color: white; text-decoration: none;' href="{% url 'users_list' %}">Users List</a></li>
              {% endif %}
            </ul>
          </div>
          {% if user.is_authenticated %}
              <div class="navbar-brand">Welcome {{user.first_name}}!</div>
              <form method="get" action="/logout/">{% csrf_token %}
                <div><button class="btn btn-danger" type="submit">Log Out</button></div>
              </form>
              
            {% endif %}
            
            
            {% if user.is_authenticated == False %}
              
              <form method="get" action="/login/">{% csrf_token %}
                <div><button class="btn btn-primary" type="submit">Log In</button></div>
              </form>
            {% endif %}
        </div>
      </nav>
      <div class="container">
        {% block content %} 
        {% endblock %}
      </div>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
    ></script> 
  </body>
</html>

templates/register.html
{% extends "base.html" %} 
{% block title %}Register{% endblock %} 
{# Load the tag library #} {% load bootstrap5 %} {# Load CSS and JavaScript #}
{% bootstrap_css %} {% bootstrap_javascript %}
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html>
  <head> </head>
  <body>
    <h1>Register a User</h1>

    <form method="post">
      {% csrf_token %} {{ form | crispy }}
      <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <p> Registered?<a href="{% url 'user_login' %}">Log In now</a></p>
  </body>
</html>
{% endblock %}

templates/url_detail.html
{% extends "base.html" %}
{% block title %}URL Detail{% endblock %} 
{% block content %}
    {% if user.is_authenticated %}
        <div class="card text-center">
            <div class="card-header"></div>
            <div class="card-body">
            <h5 class="card-title">TinyURL for: {{ url.longURL }}</h5>
            <p class="card-text">Short URL: <a href="{% url 'urls_redirect' url.short_url %}">{{ url.short_url }}</a></p>
            <p class="card-text">Visited: {{total_visits}} times!</p>
            </div>
            <div class="card-footer text-muted"></div>
            <form method="POST">{% csrf_token %} {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Edit</button>
            </form>
        </div>
    {%else%}
        <h1>Thou shalt not pass! Please <a href="{% url 'user_login' %}">Login</a> or <a href="{% url 'register' %}">Register</a></h1>
    {% endif %}

{% endblock %}

templates/urls_index.html
{% extends "base.html" %} 
{% block title %}My URLs{% endblock %} 
{% block content %}
<main class="container">
    {% if user.is_authenticated %}
        <h3>My URLs</h3>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Short URL</th>
                <th scope="col">Long URL</th>
                <th scope="col">Delete</th>
                <th scope="col">Edit</th>    
            </tr>
            </thead>
            <tbody>
            {% for url in urls %}
                <tr>
                <td>{{ url.short_url }}</td>    
                <td>{{ url.long_url }}</td>
                <td>
                    
                    <form method="POST" action="{% url 'urls_delete' url.id %}">{% csrf_token %}
                        <button class="btn btn-outline-danger" type="submit">Delete</button>
                    </form>
                </td>
                <td>
                    
                    <form  method="POST" action = "{% url 'urls_edit' url.id %}">{% csrf_token %}
                        <button class="btn btn-outline-primary" type="submit">Edit</button>
                    </form>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {%else%}
        <h1>Thou shalt not pass! Please <a href="{% url 'user_login' %}">Login</a> or <a href="{% url 'register' %}">Register</a></h1>
    {% endif %}
</main>
{% endblock %}

templates/urls_new.html
{% extends "base.html" %}
{% block title %}My URLs New{% endblock %} 
{% block content %}
    {% if user.is_authenticated %}
        <h3>Create TinyURL</h3>
        <form class="form-inline" method="POST">
            {% csrf_token %}{{ form.as_p}}
                <button type="submit" class="btn btn-primary">Create</button>
        </form>
    {%else%}
        <h1>Thou shalt not pass! Please <a href="{% url 'user_login' %}">Login</a> or <a href="{% url 'register' %}">Register</a></h1>
    {% endif %}
{% endblock %}